In [1]:
from hw2fintools import gurufocus as gf
import os
from dotenv import load_dotenv
import pandas as pd
import re


load_dotenv()
path_stockdata = os.path.join(os.environ.get('judgement_day'), 'Data--StockWatchList')
date_pattern = r"(\d\d\d\d-\d\d-\d\d)--"

In [2]:
ticker = input('Enter ticker symbol: ')
print('Ticker is: ', ticker)

Ticker is:  AMD

In [3]:
path_ticker = os.path.join(path_stockdata, ticker.upper())
div_list = []

for item in os.listdir(path_ticker):
    if 'gf-raw-dividend_history' in item and item.endswith('.csv') and not item.startswith('._'):
        div_list.append(item)

div_list_sorted = sorted(div_list, reverse=True)
div_current = div_list_sorted[0]

div_path = os.path.join(path_ticker, div_current)
div_path

'/Volumes/JudgmentDay/StockData/AMD/2025-12-09--AMD--gf-raw-dividend_history.csv'

In [4]:
price_list = []

for item in os.listdir(path_ticker):
    if 'gf-raw-price_history' in item and item.endswith('.csv') and not item.startswith('._'):
        price_list.append(item)

price_list_sorted = sorted(price_list, reverse=True)
price_current = price_list_sorted[0]

price_path = os.path.join(path_ticker, price_current)
price_path

'/Volumes/JudgmentDay/StockData/AMD/2025-12-09--AMD--gf-raw-price_history.csv'

In [5]:
div_date = re.search(date_pattern, div_path)
price_date = re.search(date_pattern, price_path)

div_match = div_date.group(1)
price_match = price_date.group(1)

if div_match == price_match:
    print('date match')
else:
    print('date mismatch')

date match

In [6]:
div_df0 = gf.div_hist_s1v1(div_path)

In [7]:
div_df1 = div_df0.loc[div_df0['DivType'] == 'regular']
div_df1 = div_df1.drop(columns=['DivRecordDate', 'DivDeclareDate', 'DivPayDate'])
div_df1 = div_df1.rename(columns={'ExDivDate': 'Date'})
div_df1

Empty DataFrame
Columns: [DivAmount, Date, DivType, Currency, DivFrequency]
Index: []

In [8]:
price_df0 = gf.price_hist_s2v1(price_path)

In [9]:
merged_df0 = pd.merge(price_df0, div_df1, on='Date', how='left')
merged_df0['DivAmount'] = merged_df0['DivAmount'].fillna(0)
merged_df0['DivFrequency'] = merged_df0['DivFrequency'].fillna(div_df1.iloc[0]['DivFrequency'])
merged_df0['DivType'] = merged_df0['DivType'].fillna(div_df1.iloc[0]['DivType'])
merged_df0['DivPayDeclared'] = merged_df0['DivAmount'].fillna(0)
merged_df0

IndexError: single positional indexer is out-of-bounds

In [10]:
div_var = 0

for index, row in merged_df0.iterrows():
    if row['DivAmount'] > 0:
        div_var = row['DivAmount']

    else:
        merged_df0.at[index, 'DivAmount'] = div_var


merged_df0['FwdDiv'] = merged_df0['DivFrequency'] * merged_df0['DivAmount']
merged_df0['FwdDivYield'] = merged_df0['FwdDiv'] / merged_df0['PricePerShare']

merged_df0

,Date,PricePerShare,DivAmount,DivType,Currency,DivFrequency,DivPayDeclared,FwdDiv,FwdDivYield
0,1986-04-02,0.804700,0.00,regular,NaN,4.0,0.0,0.00,0.000000
1,1986-04-03,0.906300,0.00,regular,NaN,4.0,0.0,0.00,0.000000
2,1986-04-04,0.906300,0.00,regular,NaN,4.0,0.0,0.00,0.000000
3,1986-04-07,0.890699,0.00,regular,NaN,4.0,0.0,0.00,0.000000
4,1986-04-08,0.906300,0.00,regular,NaN,4.0,0.0,0.00,0.000000
...,...,...,...,...,...,...,...,...,...
9995,2025-12-02,102.470000,1.27,regular,NaN,4.0,0.0,5.08,0.049575
9996,2025-12-03,105.050000,1.27,regular,NaN,4.0,0.0,5.08,0.048358
9997,2025-12-04,105.790000,1.27,regular,NaN,4.0,0.0,5.08,0.048020
9998,2025-12-05,106.580000,1.27,regular,NaN,4.0,0.0,5.08,0.047664
9999,2025-12-08,104.520000,1.27,regular,NaN,4.0,0.0,5.08,0.048603

In [11]:
aggr_df0 = merged_df0
aggr_df0 = aggr_df0.set_index('Date')
aggr_df1 = aggr_df0.groupby(aggr_df0.index.year).agg(
    SharePriceMin=pd.NamedAgg(column='PricePerShare', aggfunc='min'),
    SharePriceMax=pd.NamedAgg(column='PricePerShare', aggfunc='max'),
    SharePriceMean=pd.NamedAgg(column='PricePerShare', aggfunc='mean'),
    SharePriceMedian=pd.NamedAgg(column='PricePerShare', aggfunc='median'),
    DivYieldMin=pd.NamedAgg(column='FwdDivYield', aggfunc='min'),
    DivYieldMax=pd.NamedAgg(column='FwdDivYield', aggfunc='max'),
    DivYieldMean=pd.NamedAgg(column='FwdDivYield', aggfunc='mean'),
    DivYieldMedian=pd.NamedAgg(column='FwdDivYield', aggfunc='median'),
    DividendPaidTotalCy=pd.NamedAgg('DivPayDeclared', aggfunc='sum')
)
aggr_df1

,SharePriceMin,SharePriceMax,SharePriceMean,SharePriceMedian,DivYieldMin,DivYieldMax,DivYieldMean,DivYieldMedian,DividendPaidTotalCy
Date,,,,,,,,,
1986,0.8047,1.336000,1.030539,1.00790,0.000000,0.013428,0.004010,0.005120,0.00580
1987,0.5547,1.586000,1.116229,1.17970,0.008071,0.028160,0.012601,0.010850,0.01400
1988,0.6641,1.101600,0.938994,0.96100,0.015977,0.026502,0.019203,0.018464,0.01980
1989,1.0860,1.828199,1.451401,1.44540,0.015360,0.024309,0.018648,0.018415,0.02920
1990,0.8985,1.953200,1.521684,1.57820,0.019250,0.041848,0.025580,0.023825,0.03820
1991,1.1719,2.812500,1.852341,1.81250,0.016071,0.034133,0.022305,0.022069,0.04130
1992,2.0625,3.062500,2.498346,2.46490,0.014759,0.021915,0.018330,0.018544,0.04710
1993,2.5469,4.086000,3.219620,3.01570,0.012922,0.020731,0.016793,0.017600,0.05590
1994,3.1563,4.781300,3.808117,3.76180,0.013636,0.021879,0.017308,0.017368,0.06890
1995,3.3910,6.937500,5.107427,4.80475,0.011532,0.023592,0.016389,0.016731,0.08630
1996,5.4065,11.375000,7.452287,7.06250,0.009248,0.019458,0.014448,0.014881,0.13135
1997,9.2815,18.375000,13.339630,12.90650,0.007075,0.014006,0.009661,0.009585,0.14000
1998,11.3750,21.219000,16.981854,17.37500,0.008012,0.014945,0.010174,0.009793,0.17750
1999,13.2190,20.437500,17.211570,17.39075,0.009786,0.015130,0.011796,0.011620,0.21500
2000,15.0940,24.312500,20.194613,20.42200,0.010694,0.017225,0.013045,0.012780,0.27000
2001,12.8500,21.344000,17.345597,17.57250,0.014055,0.023346,0.017524,0.017072,0.30500
2002,10.7250,20.995000,16.117659,15.90500,0.015242,0.029837,0.020411,0.020119,0.32500
2003,12.1500,23.705000,18.016546,19.42500,0.014854,0.027984,0.019693,0.017503,0.35000
2004,22.3350,31.565000,25.948552,25.53000,0.012137,0.017014,0.014818,0.014884,0.40000
2005,27.4100,37.365000,31.560188,31.31750,0.012311,0.016782,0.014687,0.014699,0.48500
2006,35.2400,48.310000,41.299721,40.88500,0.011592,0.015891,0.013698,0.013729,0.59000
2007,44.5960,64.700000,52.680960,51.04000,0.010510,0.015952,0.013094,0.013339,0.75000
2008,25.1300,65.010000,50.347234,52.67000,0.014767,0.038201,0.020052,0.018227,0.96000
2009,21.0100,54.270000,40.155714,41.96000,0.018426,0.045693,0.026134,0.023832,1.00000
2010,43.6000,65.370000,52.725069,51.78000,0.016521,0.024771,0.020374,0.020125,1.08000
2011,45.8900,71.100000,58.754345,58.32500,0.015190,0.027021,0.020919,0.021260,1.24000
2012,55.2100,66.500000,62.044882,62.12500,0.019648,0.024633,0.021570,0.021406,1.36000
2013,66.9800,83.770000,74.827996,74.46500,0.018085,0.021671,0.019945,0.020039,1.52000
2014,73.9400,87.590000,81.095456,81.22500,0.018112,0.023803,0.021170,0.021505,1.76000
2015,68.2700,85.760000,77.567401,78.14500,0.020522,0.030467,0.026189,0.026617,2.08000
2016,63.2100,78.610000,71.129881,71.34500,0.027477,0.034172,0.030238,0.029979,2.16000
2017,66.4500,105.360000,80.705020,75.58000,0.021640,0.033713,0.028447,0.029252,2.28000
2018,84.9500,126.240000,110.139283,111.63000,0.019002,0.032961,0.024714,0.024242,2.80000
2019,88.8100,125.350000,107.895893,107.58000,0.024252,0.031528,0.027878,0.028134,3.04000
2020,85.4200,153.170000,128.042036,130.15000,0.021861,0.042145,0.027695,0.026677,3.60000
2021,147.6900,223.870000,191.502659,194.92000,0.019297,0.025632,0.021954,0.022019,4.32000
2022,98.0700,195.120000,128.350518,123.63000,0.022140,0.048945,0.037587,0.038826,4.80000
2023,88.3900,128.750000,108.979620,109.67500,0.037282,0.055210,0.044861,0.044446,4.88000
2024,101.6900,124.690000,113.077639,112.94500,0.039779,0.048776,0.043810,0.043813,4.96000
2025,80.2700,116.920000,101.278611,102.86000,0.042422,0.063286,0.050226,0.049308,3.81000

In [12]:
merged_df0.to_csv(os.path.join(path_ticker, ticker.upper() + '--DivPrice_History--s3v1.csv'))

In [13]:
aggr_df1.to_csv(os.path.join(path_ticker, ticker.upper() + '--Aggregate_Cy_DivPrice_History--s4v1.csv'))