## Data Imports & Common Vairiables

In [1]:
import os
from dotenv import load_dotenv
import pandas as pd
import plotly.express as px
import datetime

load_dotenv()
ticker = 'TXN'
path_stockdata = os.path.join(os.path.join(os.environ.get('judgement_day'), 'Data--StockWatchList'), ticker)
path_analysis_csv = os.path.join(path_stockdata, f'{ticker}--Analysis_DYT-s1v1.csv')

today = datetime.date.today()
cutoff = today.year - 20
cutoff10 = today.year - 10
cutoff5 = today.year - 5
cutoff3 = today.year - 3

## Data Frame Imports

Notable Cleaning
- Convert string dates to datetime
- Filter down to last 20 years of data
- Filter out current year in dvtagr_df as it will have incomplete data
- Convert decimal yields to numeric percentage for easy viewing

In [2]:
%%capture

dyt_df0 = pd.read_csv(os.path.join(path_stockdata, f'{ticker}--DivPrice_History-s1v1.csv'), index_col=0)
dyt_df0['Date'] = pd.to_datetime(dyt_df0['Date'])
dyt_df1 = dyt_df0[dyt_df0['Date'].dt.year >= cutoff]
dyt_df1['FwdDiv%'] = round(dyt_df0['FwdDivYield'] * 100, 2)


dytagr_df0 = pd.read_csv(os.path.join(path_stockdata, f'{ticker}--Aggregate_Cy_DivPrice_History-s1v1.csv'), index_col=0)
dytagr_df1 = dytagr_df0.query('DateCy >= @cutoff and DateCy < @today.year')
dytagr_df1['Min%'] = round(dytagr_df1['DivYieldMin'] * 100, 2)
dytagr_df1['Max%'] = round(dytagr_df1['DivYieldMax'] * 100, 2)
dytagr_df1['Mean%'] = round(dytagr_df1['DivYieldMean'] * 100, 2)
dytagr_df1['Median%'] = round(dytagr_df1['DivYieldMedian'] * 100, 2)

In [3]:
print('dyt_df1 Row Count:', len(dyt_df1))
dyt_df1

dyt_df1 Row Count: 5037

,Date,PricePerShare,DivAmount,DivType,Currency,DivFrequency,DivPayDeclared,FwdDiv,FwdDivYield,FwdDiv%
7574,2006-01-03,33.24,0.03,regular,NaN,4.0,0.0,0.12,0.003610,0.36
7575,2006-01-04,33.54,0.03,regular,NaN,4.0,0.0,0.12,0.003578,0.36
7576,2006-01-05,34.14,0.03,regular,NaN,4.0,0.0,0.12,0.003515,0.35
7577,2006-01-06,34.45,0.03,regular,NaN,4.0,0.0,0.12,0.003483,0.35
7578,2006-01-09,34.18,0.03,regular,NaN,4.0,0.0,0.12,0.003511,0.35
...,...,...,...,...,...,...,...,...,...,...
12606,2026-01-05,177.17,1.42,regular,NaN,4.0,0.0,5.68,0.032060,3.21
12607,2026-01-06,192.10,1.42,regular,NaN,4.0,0.0,5.68,0.029568,2.96
12608,2026-01-07,185.71,1.42,regular,NaN,4.0,0.0,5.68,0.030585,3.06
12609,2026-01-08,188.45,1.42,regular,NaN,4.0,0.0,5.68,0.030141,3.01
12610,2026-01-09,190.31,1.42,regular,NaN,4.0,0.0,5.68,0.029846,2.98

In [4]:
print('dytagr_df1 Row Count:', len(dytagr_df1))
dytagr_df1

dytagr_df1 Row Count: 20

,SharePriceMin,SharePriceMax,SharePriceMean,SharePriceMedian,DivYieldMin,DivYieldMax,DivYieldMean,DivYieldMedian,DivPaidTotal,Min%,Max%,Mean%,Median%
DateCy,,,,,,,,,,,,,
2006,27.0000,35.56,31.149363,30.910,0.003375,0.005604,0.004102,0.003882,0.13,0.34,0.56,0.41,0.39
2007,28.3200,39.18,33.555697,33.450,0.004527,0.013154,0.008415,0.008840,0.30,0.45,1.32,0.84,0.88
2008,14.0100,32.70,25.318573,28.160,0.012232,0.031406,0.017278,0.014205,0.41,1.22,3.14,1.73,1.42
2009,13.7700,26.85,20.726310,21.315,0.017502,0.031954,0.022332,0.020643,0.45,1.75,3.20,2.23,2.06
2010,22.5000,33.75,26.349821,25.080,0.015407,0.021333,0.018641,0.019139,0.49,1.54,2.13,1.86,1.91
2011,24.8200,36.56,31.660923,31.760,0.014223,0.024469,0.017556,0.016383,0.56,1.42,2.45,1.76,1.64
2012,26.4300,33.99,30.075377,29.560,0.020006,0.025728,0.022721,0.023004,0.51,2.00,2.57,2.27,2.30
2013,31.5528,43.91,37.607277,37.010,0.020286,0.032758,0.027405,0.028091,1.07,2.03,3.28,2.74,2.81
2014,40.8900,55.62,47.374206,46.995,0.024346,0.029347,0.025972,0.025748,1.24,2.43,2.93,2.60,2.57
2015,43.5200,59.94,53.961369,54.710,0.022689,0.031250,0.025829,0.025835,1.40,2.27,3.12,2.58,2.58
2016,48.0300,74.87,63.102500,62.125,0.021196,0.031647,0.025505,0.025936,1.64,2.12,3.16,2.55,2.59
2017,72.9200,104.82,84.333566,81.050,0.020513,0.027427,0.024753,0.024888,2.12,2.05,2.74,2.48,2.49
2018,87.8000,119.89,106.114781,108.220,0.020686,0.035080,0.024538,0.022916,2.63,2.07,3.51,2.45,2.29
2019,88.8800,131.69,115.665893,116.740,0.023388,0.034653,0.027545,0.027775,3.21,2.34,3.47,2.75,2.78
2020,93.5000,166.68,132.161443,131.440,0.023241,0.038503,0.028266,0.027510,3.72,2.32,3.85,2.83,2.75
2021,162.1100,201.29,186.063909,188.415,0.020269,0.025168,0.022451,0.021950,4.21,2.03,2.52,2.25,2.19
2022,148.3400,191.01,169.719721,170.010,0.024083,0.031689,0.027562,0.027588,4.69,2.41,3.17,2.76,2.76
2023,140.5000,186.08,168.337620,169.970,0.026655,0.037011,0.029849,0.029216,5.02,2.67,3.70,2.98,2.92
2024,156.8500,220.29,188.354425,193.940,0.024261,0.033153,0.028023,0.027051,5.26,2.43,3.32,2.80,2.71
2025,145.6100,221.25,182.848240,182.570,0.024588,0.037360,0.030226,0.029861,5.50,2.46,3.74,3.02,2.99

## View Aggregate Yield Data By year

In [5]:
dytagr_df1[['Min%', 'Max%', 'Mean%', 'Median%']]

        Min%  Max%  Mean%  Median%
DateCy
2006    0.34  0.56   0.41     0.39
2007    0.45  1.32   0.84     0.88
2008    1.22  3.14   1.73     1.42
2009    1.75  3.20   2.23     2.06
2010    1.54  2.13   1.86     1.91
2011    1.42  2.45   1.76     1.64
2012    2.00  2.57   2.27     2.30
2013    2.03  3.28   2.74     2.81
2014    2.43  2.93   2.60     2.57
2015    2.27  3.12   2.58     2.58
2016    2.12  3.16   2.55     2.59
2017    2.05  2.74   2.48     2.49
2018    2.07  3.51   2.45     2.29
2019    2.34  3.47   2.75     2.78
2020    2.32  3.85   2.83     2.75
2021    2.03  2.52   2.25     2.19
2022    2.41  3.17   2.76     2.76
2023    2.67  3.70   2.98     2.92
2024    2.43  3.32   2.80     2.71
2025    2.46  3.74   3.02     2.99

## Calc Mean, Median & Rolling

In [6]:
mean20 = round(dyt_df1['FwdDiv%'].mean(), 2)
median20 = round(dyt_df1['FwdDiv%'].median(), 2)

dyt_df1_l10 = dyt_df1[dyt_df1['Date'].dt.year >= cutoff10]
mean10 = round(dyt_df1_l10['FwdDiv%'].mean(), 2)
median10 = round(dyt_df1_l10['FwdDiv%'].median(), 2)

dyt_df1_l5 = dyt_df1[dyt_df1['Date'].dt.year >= cutoff5]
mean5 = round(dyt_df1_l5['FwdDiv%'].mean(), 2)
median5 = round(dyt_df1_l5['FwdDiv%'].median(), 2)

dyt_df1_l3 = dyt_df1[dyt_df1['Date'].dt.year >= cutoff3]
mean3 = round(dyt_df1_l3['FwdDiv%'].mean(), 2)
median3 = round(dyt_df1_l3['FwdDiv%'].median(), 2)

print(f'The 20 year mean is: {mean20}%')
print(f'The 20 year median is: {median20}%')
print()
print(f'The 10 year mean is: {mean10}%')
print(f'The 10 year median is: {median10}%')
print()
print(f'The 5 year mean is: {mean5}%')
print(f'The 5 year median is: {median5}%')
print()
print(f'The 3 year mean is: {mean3}%')
print(f'The 3 year median is: {median3}%')
print()

The 20 year mean is: 2.3%
The 20 year median is: 2.48%

The 10 year mean is: 2.69%
The 10 year median is: 2.67%

The 5 year mean is: 2.76%
The 5 year median is: 2.78%

The 3 year mean is: 2.94%
The 3 year median is: 2.92%

## DYT Gate
- The Gate is the Dividend Yield where the company is considered fair value

In [7]:
gate = 2.9
gate10 = round((gate * .1) + gate, 2)
gate20 = round((gate * .20) + gate, 2)

print(f'The DYT Gate is: {gate}%')
print(f'The DYT Gate with 10 percent margin of error is: {gate10}%')
print(f'The DYT Gate with 25 percent margin of error is: {gate20}%')

The DYT Gate is: 2.9%
The DYT Gate with 10 percent margin of error is: 3.19%
The DYT Gate with 25 percent margin of error is: 3.48%

## DYT Plot

In [8]:
fig1 = px.line(dyt_df1, x='Date', y='FwdDiv%', title='Fwd Yield Per Date')
fig1.update_traces(line_color='blue')
fig1.add_hline(y=gate, line_dash='dot', annotation_text='Gate', annotation_position='bottom left', line_color='red')
fig1.add_hline(y=gate10, line_dash='dot', annotation_text='Gate10', annotation_position='bottom left', line_color='yellow')
fig1.add_hline(y=gate20, line_dash='dot', annotation_text='Gate20', annotation_position='bottom left', line_color='green')
fig1.show()

## Stored Analysis Output

In [9]:
metrics_json = {
    "type": "dyt",
    "date": today.strftime('%Y-%m-%d'),
    "dyt_data_type": "numeric percentage",
    "dyt_gate": gate,
    "dyt_gate_10%_mos": gate10,
    "dyt_gate_20%_mos": gate20,
}

metrics_json

{'type': 'dyt',
 'date': '2026-02-18',
 'dyt_data_type': 'numeric percentage',
 'dyt_gate': 2.9,
 'dyt_gate_10%_mos': 3.19,
 'dyt_gate_20%_mos': 3.48}

In [10]:
metrics_df = pd.DataFrame([metrics_json])
metrics_df

,type,date,dyt_data_type,dyt_gate,dyt_gate_10%_mos,dyt_gate_20%_mos
0,dyt,2026-02-18,numeric percentage,2.9,3.19,3.48

In [11]:
if os.path.isfile(path_analysis_csv):
    metrics_df.to_csv(path_analysis_csv, mode='a', header=False, index=False)
else:
    metrics_df.to_csv(path_analysis_csv, mode='w', header=True, index=False)

## Notebook End